"""Definitions for Itho Demand Flow sensors added to MQTT."""

from homeassistant.components.sensor import SensorStateClass
from homeassistant.const import (
    CONCENTRATION_PARTS_PER_MILLION,
    PERCENTAGE,
    EntityCategory,
    UnitOfTime,
    UnitOfVolumeFlowRate,
)

from .base_definitions import (
    IthoBinarySensorEntityDescription,
    IthoSensorEntityDescription,
)

DEMAND_FLOW_BINARY_SENSORS: tuple[IthoBinarySensorEntityDescription, ...] = (
    IthoBinarySensorEntityDescription(
        json_field="Status normal",
        key="status_normal",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    IthoBinarySensorEntityDescription(
        json_field="Status high extractor hood",
        key="status_high_extractor",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    IthoBinarySensorEntityDescription(
        json_field="Status high bathroom",
        key="status_high_bathroom",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    IthoBinarySensorEntityDescription(
        json_field="Status high extractor hood and bath",
        key="status_high_extractor_bathroom",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    IthoBinarySensorEntityDescription(
        json_field="Status timer",
        key="status_timer",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    IthoBinarySensorEntityDescription(
        json_field="Status manual control",
        key="status_manual_control",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    IthoBinarySensorEntityDescription(
        json_field="Status eco comfort",
        key="status_eco comfort",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    IthoBinarySensorEntityDescription(
        json_field="Status limited ventilation",
        key="status_limited_ventilation",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    IthoBinarySensorEntityDescription(
        json_field="Status not at home",
        key="status_notathome",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
)

DEMAND_FLOW_SENSORS: tuple[IthoSensorEntityDescription, ...] = (
    IthoSensorEntityDescription(
        json_field="Operating mode",
        key="operating_mode",
        icon="mdi:knob",
        is_selected_entity=True,
    ),
    IthoSensorEntityDescription(
        json_field="Operating status",
        key="operating_status",
        icon="mdi:knob",
        is_selected_entity=True,
    ),
    IthoSensorEntityDescription(
        json_field="RH extractor (%)",
        key="rh_extractor",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="RH kitchen (%)",
        key="rh_kitchen",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="RH toilet 1 (%)",
        key="rh_toilet1",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="RH living room 1 (%)",
        key="rh_livingroom1",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="RH living room 2 (%)",
        key="rh_livingroom2",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="RH laundry room (%)",
        key="rh_laundryroom",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="RH bathroom 1 (%)",
        key="rh_bathroom1",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IthoSensorEntityDescription(
        json_field="RH bathroom 2 (%)",
        key="rh_bathroom2",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IthoSensorEntityDescription(
        json_field="RH bedroom 1 (%)",
        key="rh_bedroom1",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="RH bedroom 2 (%)",
        key="rh_bedroom2",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="RH bedroom 3 (%)",
        key="rh_bedroom3",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="RH bedroom 4 (%)",
        key="rh_bedroom4",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="exhaust fan (%)",
        key="exhaust_fan",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IthoSensorEntityDescription(
        json_field="supply fan (%)",
        key="supply_fan",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IthoSensorEntityDescription(
        json_field="CO2 plenum (ppm)",
        key="co2_plenum",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="CO2 calculated (ppm)",
        key="co2_calculated",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 extractor (ppm)",
        key="calc_co2_extractor",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 kitchen (ppm)",
        key="calc_co2_kitchen",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 toilet1 (ppm)",
        key="calc_co2_toilet1",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 living room 1 (ppm)",
        key="calc_co2_livingroom1",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 living room 2 (ppm)",
        key="calc_co2_livingroom2",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 washroom (ppm)",
        key="calc_co2_laundryroom",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 bathroom1 (ppm)",
        key="calc_co2_bathroom1",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 bath2 + toilet2 (ppm)",
        key="calc_co2_bathroom2",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 bedroom 1 (ppm)",
        key="calc_co2_bedroom1",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 bedroom 2 (ppm)",
        key="calc_co2_bedroom2",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 bedroom 3 (ppm)",
        key="calc_co2_bedroom3",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated CO2 bedroom 4 (ppm)",
        key="calc_co2_bedroom4",
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated pos valve extractor",
        key="calc_pos_extractor",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="calculated pos flap kitchen",
        key="calc_pos_kitchen",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated pos flap toilet 1",
        key="calc_pos_toilet1",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated pos flap living room 1",
        key="calc_pos_livingroom1",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated pos flap living room 2",
        key="calc_pos_livingroom2",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated pos flap laundry room",
        key="calc_pos_laundryroom",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated pos flap bathroom1",
        key="calc_pos_bathroom1",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated pos valve bath2+toilet2",
        key="calc_pos_bathroom2",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated pos valve bedroom1",
        key="calc_pos_bedroom1",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated pos flap bedroom 2",
        key="calc_pos_bedroom2",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated pos flap bedroom 3",
        key="calc_pos_bedroom3",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated pos damper bedroom 4",
        key="calc_pos_bedroom4",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow extractor hood (m3_h)",
        key="calc_flow_extractor",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow kitchen (m3_h)",
        key="calc_flow_kitchen",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow toilet 1 (m3_h)",
        key="calc_flow_toilet1",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow living room 1 (m3_h)",
        key="calc_flow_livingroom1",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow living room 2 (m3_h)",
        key="calc_flow_livingroom2",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow laundry room (m3_h)",
        key="calc_flow_laundryroom",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow bathroom 1 (m3_h)",
        key="calc_flow_bathroom1",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow bath2+toilet2 (m3_h)",
        key="calc_flow_bathroom2",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow bedroom1 (m3_h)",
        key="calc_flow_bedroom1",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow bedroom 2 (m3_h)",
        key="calc_flow_bedroom2",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow bedroom 3 (m3_h)",
        key="calc_flow_bedroom3",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Calculated Flow bedroom 4 (m3_h)",
        key="calc_flow_bedroom4",
        native_unit_of_measurement=UnitOfVolumeFlowRate.CUBIC_METERS_PER_HOUR,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
    ),
    IthoBinarySensorEntityDescription(
        json_field="Error",
        key="error",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    IthoSensorEntityDescription(
        json_field="Measuring interval (sec)",
        key="measuring_interval",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Timer extractor (sec)",
        key="timer_extractor",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Time increase bathroom 1 (sec)",
        key="time_increase_bathroom1",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Time increment bathroom 2 (sec)",
        key="time_increase_bathroom2",
        native_unit_of_measurement=UnitOfTime.SECONDS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="CO2 measurement room",
        key="co2_measurement_room",
        icon="mdi:knob",
        is_selected_entity=False,
        entity_registry_enabled_default=False,
    ),
    IthoSensorEntityDescription(
        json_field="Measurement method",
        key="measurement_method",
        icon="mdi:knob",
        is_selected_entity=False,
        entity_category=EntityCategory.DIAGNOSTIC,
        entity_registry_enabled_default=False,
    ),
)
